server:
  port: 7090
  servlet:
    context-path: /auth

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

keycloak:
  realm: reze-music
  domain: localhost:8080
#  domain: keycloak.ignacio.com
  adminClientId: admin-cli
  adminClientSecret: iZ8jEvr5P5hIpJyUaDRlQEFo5RcbzzCb
  urls:
    auth: https://${keycloak.domain}

spring:
  profile:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}
